[package]
name = "ainoio-example"
version = "1.1.0"
authors = ["Olli Aalto <olli.aalto@unikie.com>"]
edition = "2021"
license = "Apache-2.0"
description = "Example for Aino.io agent"
repository = "https://github.com/Aino-io/aino-agent-rust/example"

[dependencies]
ainoio-agent = { path = ".." }
